import { type PricingPlan, type FeedEvent, type TrackedPackage, type AlertItem, type DashboardStats } from "@/types";

export const PRICING_PLANS: PricingPlan[] = [
  {
    name: "Free",
    tier: "free",
    price: 0,
    description: "For individual developers getting started.",
    features: [
      "Track up to 10 packages",
      "Daily digest emails",
      "Public advisory feed",
      "Basic severity filtering",
      "Community support",
    ],
  },
  {
    name: "Individual",
    tier: "individual",
    price: 19,
    description: "For developers who ship to production.",
    features: [
      "Track up to 100 packages",
      "Real-time alerts",
      "Slack & email integrations",
      "Upload package.json",
      "Alert history & search",
      "Priority support",
    ],
    highlighted: true,
  },
  {
    name: "Team",
    tier: "team",
    price: 49,
    description: "For teams monitoring multiple projects.",
    features: [
      "Unlimited packages",
      "All integrations",
      "PagerDuty & Telegram",
      "Team members",
      "Export & API access",
      "Dedicated support",
      "Custom alert rules",
    ],
  },
];

export const MOCK_STATS: DashboardStats = {
  totalPackages: 147,
  activeAlerts: 12,
  criticalIssues: 3,
  integrationsConnected: 4,
};

export const MOCK_FEED: FeedEvent[] = [
  {
    id: "1",
    type: "VULNERABILITY",
    title: "Critical prototype pollution in lodash",
    severity: "critical",
    packageName: "lodash",
    ecosystem: "npm",
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
    description: "A prototype pollution vulnerability was found in lodash versions < 4.17.21 that allows attackers to modify object prototypes.",
  },
  {
    id: "2",
    type: "SUSPICIOUS_RELEASE",
    title: "Suspicious release detected for axios",
    severity: "high",
    packageName: "axios",
    ecosystem: "npm",
    timestamp: new Date(Date.now() - 1000 * 60 * 8),
    description: "An unusual release pattern was detected for axios@1.6.3. The release was made by a new maintainer with obfuscated code changes.",
  },
  {
    id: "3",
    type: "COMPROMISE",
    title: "Maintainer account compromise reported",
    severity: "critical",
    packageName: "event-stream",
    ecosystem: "npm",
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    description: "The maintainer account for event-stream was compromised. Malicious code was injected targeting cryptocurrency wallets.",
  },
  {
    id: "4",
    type: "REGISTRY_REMOVAL",
    title: "Package removed from npm registry",
    severity: "medium",
    packageName: "faker",
    ecosystem: "npm",
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    description: "The faker package was deliberately emptied by its maintainer. All versions now contain no functional code.",
  },
  {
    id: "5",
    type: "VULNERABILITY",
    title: "Server-side request forgery in next.js",
    severity: "high",
    packageName: "next",
    ecosystem: "npm",
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    description: "A SSRF vulnerability was found in Next.js middleware that allows attackers to bypass authorization checks.",
  },
  {
    id: "6",
    type: "MALWARE",
    title: "Malicious package typosquatting express",
    severity: "critical",
    packageName: "expresss",
    ecosystem: "npm",
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    description: "A malicious package 'expresss' was found typosquatting the popular 'express' framework. It exfiltrates environment variables.",
  },
  {
    id: "7",
    type: "VULNERABILITY",
    title: "SQL injection in sequelize",
    severity: "high",
    packageName: "sequelize",
    ecosystem: "npm",
    timestamp: new Date(Date.now() - 1000 * 60 * 90),
    description: "A SQL injection vulnerability was found in sequelize ORM when using raw queries with user-provided input.",
  },
  {
    id: "8",
    type: "LICENSE_CHANGE",
    title: "License changed from MIT to SSPL",
    severity: "medium",
    packageName: "mongodb",
    ecosystem: "npm",
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
    description: "MongoDB driver changed its license from MIT to Server Side Public License, which may affect commercial usage.",
  },
  {
    id: "9",
    type: "MAINTAINER_CHANGE",
    title: "Primary maintainer transferred ownership",
    severity: "low",
    packageName: "chalk",
    ecosystem: "npm",
    timestamp: new Date(Date.now() - 1000 * 60 * 180),
    description: "The primary maintainer of chalk transferred package ownership to a new npm account with no prior publishing history.",
  },
  {
    id: "10",
    type: "VULNERABILITY",
    title: "ReDoS vulnerability in validator.js",
    severity: "medium",
    packageName: "validator",
    ecosystem: "npm",
    timestamp: new Date(Date.now() - 1000 * 60 * 240),
    description: "A regular expression denial of service vulnerability was found in the isEmail validator function.",
  },
];

export const MOCK_PACKAGES: TrackedPackage[] = [
  { id: "1", packageName: "react", currentVersion: "18.2.0", latestSafeVersion: "18.2.0", ecosystem: "npm", status: "safe", lastAlertAt: null, muted: false },
  { id: "2", packageName: "next", currentVersion: "14.1.0", latestSafeVersion: "14.1.4", ecosystem: "npm", status: "vulnerable", lastAlertAt: new Date(Date.now() - 1000 * 60 * 45), muted: false },
  { id: "3", packageName: "lodash", currentVersion: "4.17.19", latestSafeVersion: "4.17.21", ecosystem: "npm", status: "vulnerable", lastAlertAt: new Date(Date.now() - 1000 * 60 * 2), muted: false },
  { id: "4", packageName: "axios", currentVersion: "1.6.2", latestSafeVersion: "1.6.5", ecosystem: "npm", status: "vulnerable", lastAlertAt: new Date(Date.now() - 1000 * 60 * 8), muted: false },
  { id: "5", packageName: "express", currentVersion: "4.18.2", latestSafeVersion: "4.18.2", ecosystem: "npm", status: "safe", lastAlertAt: null, muted: false },
  { id: "6", packageName: "prisma", currentVersion: "5.8.0", latestSafeVersion: "5.8.1", ecosystem: "npm", status: "safe", lastAlertAt: null, muted: false },
  { id: "7", packageName: "zod", currentVersion: "3.22.4", latestSafeVersion: "3.22.4", ecosystem: "npm", status: "safe", lastAlertAt: null, muted: true },
  { id: "8", packageName: "typescript", currentVersion: "5.3.3", latestSafeVersion: "5.3.3", ecosystem: "npm", status: "safe", lastAlertAt: null, muted: false },
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: "1",
    packageName: "lodash",
    title: "Prototype Pollution in lodash",
    severity: "critical",
    status: "new",
    detectedAt: new Date(Date.now() - 1000 * 60 * 2),
    sourceUrl: "https://github.com/advisories/GHSA-jf85-cpcp-j695",
    summary: "Versions of lodash prior to 4.17.21 are vulnerable to prototype pollution via the template function.",
    affectedVersions: "< 4.17.21",
    patchedVersions: "4.17.21",
  },
  {
    id: "2",
    packageName: "axios",
    title: "Server-Side Request Forgery in axios",
    severity: "high",
    status: "new",
    detectedAt: new Date(Date.now() - 1000 * 60 * 8),
    sourceUrl: "https://github.com/advisories/GHSA-wf5p-g6vw-rhxx",
    summary: "Axios before 1.6.3 is vulnerable to SSRF when using a proxy. An attacker can bypass the proxy configuration.",
    affectedVersions: "< 1.6.3",
    patchedVersions: "1.6.3",
  },
  {
    id: "3",
    packageName: "next",
    title: "Authorization bypass in Next.js middleware",
    severity: "high",
    status: "acknowledged",
    detectedAt: new Date(Date.now() - 1000 * 60 * 45),
    sourceUrl: "https://github.com/advisories/GHSA-gp8f-8m3g-qvj9",
    summary: "Next.js middleware can be bypassed by adding specific headers, allowing unauthorized access to protected routes.",
    affectedVersions: ">= 12.0.0, < 14.1.4",
    patchedVersions: "14.1.4",
  },
  {
    id: "4",
    packageName: "express",
    title: "Open Redirect in express",
    severity: "medium",
    status: "resolved",
    detectedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    sourceUrl: "https://github.com/advisories/GHSA-rv95-896h-c2vc",
    summary: "Express.js versions before 4.18.2 are vulnerable to an open redirect attack via the redirect method.",
    affectedVersions: "< 4.18.2",
    patchedVersions: "4.18.2",
  },
  {
    id: "5",
    packageName: "sequelize",
    title: "SQL Injection in sequelize",
    severity: "high",
    status: "new",
    detectedAt: new Date(Date.now() - 1000 * 60 * 90),
    sourceUrl: "https://github.com/advisories/GHSA-wrh2-8pf6-pcrq",
    summary: "Sequelize ORM is vulnerable to SQL injection when using replacements in raw queries without proper sanitization.",
    affectedVersions: "< 6.35.2",
    patchedVersions: "6.35.2",
  },
];

export const SEVERITY_CONFIG = {
  critical: { label: "Critical", color: "text-[var(--severity-critical)]", bg: "bg-[var(--severity-critical-bg)]", border: "border-[var(--severity-critical-ring)]", badge: "bg-[var(--severity-critical-bg)] text-[var(--severity-critical)] ring-1 ring-inset ring-[var(--severity-critical-ring)]", dot: "bg-[var(--severity-critical)]" },
  high: { label: "High", color: "text-[var(--severity-high)]", bg: "bg-[var(--severity-high-bg)]", border: "border-[var(--severity-high-ring)]", badge: "bg-[var(--severity-high-bg)] text-[var(--severity-high)] ring-1 ring-inset ring-[var(--severity-high-ring)]", dot: "bg-[var(--severity-high)]" },
  medium: { label: "Medium", color: "text-[var(--severity-medium)]", bg: "bg-[var(--severity-medium-bg)]", border: "border-[var(--severity-medium-ring)]", badge: "bg-[var(--severity-medium-bg)] text-[var(--severity-medium)] ring-1 ring-inset ring-[var(--severity-medium-ring)]", dot: "bg-[var(--severity-medium)]" },
  low: { label: "Low", color: "text-[var(--severity-low)]", bg: "bg-[var(--severity-low-bg)]", border: "border-[var(--severity-low-ring)]", badge: "bg-[var(--severity-low-bg)] text-[var(--severity-low)] ring-1 ring-inset ring-[var(--severity-low-ring)]", dot: "bg-[var(--severity-low)]" },
  info: { label: "Info", color: "text-muted-foreground/70", bg: "bg-muted/60", border: "border-border/50", badge: "bg-muted/60 text-muted-foreground/70 ring-1 ring-inset ring-border/50", dot: "bg-muted-foreground/40" },
} as const;

export const SIGNAL_TYPE_CONFIG = {
  VULNERABILITY: { label: "Vulnerability", icon: "shield-alert" },
  MALWARE: { label: "Malware", icon: "bug" },
  COMPROMISE: { label: "Compromise", icon: "skull" },
  DEPRECATION: { label: "Deprecation", icon: "archive" },
  LICENSE_CHANGE: { label: "License Change", icon: "file-text" },
  MAINTAINER_CHANGE: { label: "Maintainer Change", icon: "user-x" },
  REGISTRY_REMOVAL: { label: "Registry Removal", icon: "trash-2" },
  SUSPICIOUS_RELEASE: { label: "Suspicious Release", icon: "alert-triangle" },
} as const;
